version: '3.9'

services:
  api:
    image: fargate-okta/api:latest
    build: ./api
    ports:
      - 8000:8000
    depends_on: 
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis_data:/redis_data

volumes:
  redis_data: