FROM python:3
WORKDIR /app
ENV PYTHONPATH=/app/src
ENV ENV=prod
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0"]